---
- name: artifactory | Install dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - unzip
    - net-tools
    - openjdk-8-jdk
  tags: artifactory

- name: artifactory | Download artifactory zip
  get_url: url={{ artifactory_zip_url }} dest=/opt/{{ artifactory_zip_file }}

- name: artifactory | Extract artifactory
  shell: unzip /opt/{{ artifactory_zip_file }} -d /opt  creates={{ artifactory_dir }}


- name: artifactory | Getting in to installation directory
  shell: cd /opt/{{ artifactory_version }}/bin

- name: copy and run start.sh
  shell: cd /opt/{{ artifactory_version }}/bin; nohup ./artifactory.sh &

  #- name: artifactory| start artifactory
  #shell: bash /opt/{{ artifactory_version }}/bin/artifactoryctl start
  #register: result2
  #- debug: var=result2

  #- name: artifactory | Start/Restart artifactory
  #service: name=artifactory state=started
